// Approximate swatches, not a guarantee of how a finish appears under lighting.
export const PHONE_COLORS: Record<string, readonly [string,string]> = {
  "cloud brocade white":["Парчовый белый","#ebe8e1"], "nebula red":["Красный","#a54443"],
  "blush gold":["Пудровый розовый","#e6c5b7"], "lake cyan":["Лазурно-голубой","#99bec0"],
  "golden black":["Чёрный","#2d2d2c"], "lavender purple":["Лавандовый","#b5a3bc"],
  "glazed red":["Глянцевый красный","#a73536"], "glazed white":["Глянцевый белый","#ecece8"],
  "glazed black":["Глянцевый чёрный","#292929"], "prestige gold":["Сверкающий золотой","#cdb782"],
  "velvet gold":["Матовый золотой","#dfd1b4"], "velvet white":["Матовый белый","#eeeeea"],
  "velvet black":["Матовый чёрный","#28292a"], "orange ocean":["Оранжево-голубой","#d99772"],
  "blaze purple":["Бежево-фиолетовый","#b4a0b4"], "graphite black":["Графитовый чёрный","#343435"],
  "guava soda":["Розово-зелёный","#d3afaf"], "orange soda":["Оранжевый","#e1a169"],
  "coconut white":["Белый","#ecebe5"], "mulberry black":["Чёрный","#353137"],
  "sprout green":["Светло-зелёный","#bec8ac"], "desert gold":["Песочный золотой","#d5c4a8"],
  "velvet grey":["Бархатный серый","#999b9b"], "golden white":["Золотисто-белый","#e9e4d8"],
  "sunrise gold":["Золотой рассвет","#dbcca4"], "sky cyan":["Небесный голубой","#c1d7d0"],
  "reddish brown":["Красно-коричневый","#956658"], "midnight black":["Полночный чёрный","#2a2b2d"],
  "green silk":["Шёлковый зелёный","#567b67"], "black velvet":["Бархатный чёрный","#313131"],
  "pink satin":["Атласный розовый","#d4b6ae"], "midnight ocean":["Тёмно-синий","#354357"],
  "arctic dawn":["Арктический белый","#ecebe6"], "black eclipse":["Чёрный","#2d2d2e"],
  "mint breeze":["Мятный","#b4c3b2"], "charcoal black":["Угольный чёрный","#343536"],
  "electric violet":["Фиолетовый","#b3a5c0"], "sand storm":["Песочный","#d9ccba"],
  "ultra violet":["Сиреневый","#c5bfd1"], "infinite black":["Чёрный","#303132"],
  "marble sands":["Мраморный белый","#e7e4da"], "dry ice":["Ледяной голубой","#bdcbd4"],
  "phantom grey":["Тёмно-серый","#555759"], "marble mist":["Мраморный белый","#ecebe8"],
  "nexus blue":["Синий","#4c6485"], "black infinity":["Чёрный","#333537"],
};
