"use client";

import { useState } from "react";
import { PhoneField, phoneWithCountryCode } from "@/components/PhoneField";

export function WarrantyClaimForm() {
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [product, setProduct] = useState(""); const [problem, setProblem] = useState(""); const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  async function submit(event: React.FormEvent) { event.preventDefault(); setStatus("sending"); try { const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerName: name, customerPhone: phoneWithCountryCode("+7", phone), comment: `Гарантийный случай. Товар: ${product}. Проблема: ${problem}`, items: [] }) }); if (!response.ok) throw new Error(); setStatus("sent"); } catch { setStatus("error"); } }
  return <section id="warranty-form" className="scroll-mt-24 rounded-3xl bg-zinc-50 p-6 sm:p-8"><h2 className="font-display text-2xl font-semibold text-foreground">Гарантийный случай</h2><p className="mt-2 text-sm leading-6 text-zinc-600">Опишите проблему — менеджер передаст обращение в гарантийный отдел.</p>{status === "sent" ? <p className="mt-6 rounded-xl bg-white p-4 text-sm text-zinc-700">Обращение принято. Мы свяжемся с вами по телефону.</p> : <form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Ваше имя" className="rounded-xl border border-zinc-300 px-4 py-3 text-base outline-none focus:border-accent" /><input required value={product} onChange={(e) => setProduct(e.target.value)} placeholder="Товар или модель устройства" className="rounded-xl border border-zinc-300 px-4 py-3 text-base outline-none focus:border-accent" /><div className="sm:col-span-2"><PhoneField countryCode="+7" onCountryCodeChange={() => {}} phone={phone} onPhoneChange={setPhone} allowCountrySelect={false} className="text-foreground" /></div><textarea required value={problem} onChange={(e) => setProblem(e.target.value)} placeholder="Опишите проблему: когда появилась, что происходит, есть ли повреждения" rows={5} className="sm:col-span-2 rounded-xl border border-zinc-300 px-4 py-3 text-base outline-none focus:border-accent" /><button disabled={status === "sending"} className="w-full rounded-full bg-brand px-6 py-3 font-display text-sm font-medium text-white hover:bg-brand-dark sm:w-fit">{status === "sending" ? "Отправляем…" : "Отправить обращение"}</button>{status === "error" && <p className="text-sm text-[#f95d51]">Не удалось отправить обращение.</p>}</form>}</section>;
}
